version: "2.1"
services:
    openvpn-as:
        image: ghcr.io/linuxserver/openvpn-as
        container_name: openvpn
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Stockholm
        volumes:
            - /media/saga/Media/Containers/vpn/data:/config
        ports:
            - 943:943
            - 9443:9443
            - 1194:1194/udp
        restart: unless-stopped
