version: '3.1'
services:
  pihole:
    image: pihole/pihole:v4.0_armhf
    volumes:
      - "/var/log/pihole.log:/var/log/pihole.log"
      - "/media/data/Containers/pihole-sycamore:/etc/pihole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80"
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP=192.168.11.2
      - VIRTUAL_HOST=pihole.sycamore.lan
      - DNS1=208.67.222.222 # OpenDNS
      - DNS2=172.104.136.243 # opennic.org
      - WEBPASSWORD='/run/secrets/web-password'
    extra_hosts:
      - "sycamore sycamore.lan:192.168.11.2"
      - "nodered nodered.sycamore.lan:192.168.11.2"
      - "willow willow.lan:192.168.11.4"
      - "plex plex.sycamore.lan:192.168.11.2"
      - "pihole.sycamore.lan:192.168.11.2"
      - "pihole.willow.lan:192.168.11.2"
      - "sync.sycamore.lan:192.168.11.2"
      - "sync.willow.lan:192.168.11.2"
      - "ziggy ziggy.lan:192.168.11.3"
      - "miniflux miniflux.sycamore.lan:192.168.11.2"
    secrets:
      - web-password
    restart: always
    container_name: pihole
secrets:
  web-password:
    file: ./secrets/web-password
