# In Progress...
version: 1
services:
    caddy:
        build: /caddy/.
        volumes:
            - "/media/ham/caddy/Caddyfile:/etc/Caddyfile"
            - "/media/ham/caddy/.caddy:/root/.caddy"
            - "/media/ham/caddy/sites/:/srv"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        container_name: caddy

    homeassistant:
        build: /homeassistant/.
        volumes:
            - "/media/ham/homeassistant/:/config"
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/log/cidcall.log:/var/log/cidcall.log"
            - "/home/pilot/hassdeps:/config/deps"
        devices:
            - "/dev/ttyACM0:/zwaveusbstick:rwm"
        network_mode: "host"
        restart: always
        container_name: homeassistant

    mqtt:
        image: pascaldevink/rpi-mosquitto
        volumes:
            - "/media/ham/mqtt/config:/mqtt/config:ro"
            - "/media/ham/mqtt/log:/mqtt/log"
            - "/media/ham/mqtt/data/:/mqtt/data/"
        ports:
            - "1883:1883"
            - "9001:9001"
        restart: always
        container_name: mqtt

    nodered:
        build: /node-red/.
        volumes:
            - "/media/ham/node-red/:/data/"
        ports:
            - "1880:1880"
        environment:
            - FLOWS=flows.json
        network_mode: "host"
        restart: always
        container_name: nodered

    unicorn:
        build: /unicorn/.
        volumes:
            - "/media/ham/unicorn/:/data/"
        devices:
            - "/dev/ttyAMA0:/dev/ttyAMA0"
            - "/dev/mem:/dev/mem"
        command: python server.py
        privileged: true
        restart: always
        container_name: unicorn

    watchtower:
        image: armhfbuild/watchtower
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        command: --interval 1800 --cleanup homeassistant mqtt pihole watchtower
        restart: always
        container_name: watchtower

    # optional
    ncid:
        build: /ncid/.
        volumes:
            - "/var/log/ncidd.log:/var/log/ncidd.log"
            - "/var/log/cidcall.log:/var/log/cidcall.log"
            - "/media/ham/ncid/:/etc/ncid/"
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        ports:
            - "3333:3333"
        restart: always
        container_name: ncid

    # optional
    pihole:
        image: diginc/pi-hole:arm
        volumes:
            - "/var/log/pihole.log:/var/log/pihole.log"
            - "/media/ham/pihole/:/etc/pihole/"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8053:80"
        cap_add:
            - NET_ADMIN
        environment:
            - ServerIP="192.168.11.2"
            - VIRTUAL_HOST="pihole.sycamore.lan"
            - DNS1="5.9.49.12"
            - DNS2="87.98.175.85"
        extra_hosts:
            - "sycamore sycamore.lan:192.168.11.2"
            - "pihole pihole.sycamore.lan:192.168.11.2"
            - "ziggy ziggy.sycamore.lan:192.168.11.3"
        restart: always
        container_name: pihole
