version: '2'
services:
    caddy:
        image: yobasystems/alpine-caddy:php
        volumes:
            - "/media/saga/Media/Containers/caddy/Caddyfile:/etc/Caddyfile"
            - "/media/saga/Media/Containers/caddy/.caddy:/root/.caddy"
            - "/media/saga/Media/Containers/caddy/sites/:/srv"
        ports:
            - "80:80"
            - "443:443"
            - "8811:8811"
        restart: always
        network_mode: host
        container_name: caddy
