version: '2'
services:
    caddy:
        build: .
        volumes:
            - "/mnt/data/Containers/caddy/Caddyfile:/etc/Caddyfile"
            - "/mnt/data/Containers/caddy/.caddy:/root/.caddy"
            - "/mnt/data/Containers/caddy/sites/:/srv"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        container_name: caddy

