version: '2.1'
services:
    mycroft:
        image: mycroft
        volumes:
            - "/home/pilot/mycroft/data/mycroft.conf:/root/.mycroft/mycroft.conf:ro"
            - "/home/pilot/mycroft/data/identity:/root/.mycroft/identity"
            - "/home/pilot/mycroft/asoundrc:/root/.asoundrc"
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/asound.conf:/etc/asound.conf:ro"
        tmpfs:
            - "/tmpfs:size=10m,uid=1001,rw"
        devices:
            - "/dev/snd:/dev/snd:rwm"
        ports:
            - "8181:8181"
        network_mode: host
        restart: always
        environment:
            - PULSE_SERVER=tcp:localhost
            - PGID=1001
            - PUID=1001
        container_name: mycroft
