version: '2'
services:
    pulseaudio:
        image: woahbase/alpine-pulseaudio:armhf
        volumes:
            - "/etc/asound.conf:/etc/asound.conf:ro"
            - "/etc/localtime:/etc/localtime:ro"
            - "/var/run/dbus:/var/run/dbus"
        devices:
            - "/dev/snd:/dev/snd:rwm"
        ports:
            - "4713:4713"
        environment:
            - PGID=1001
            - PUID=1001
            - DISABLEBLUETOOTH=true
        restart: always
        privileged: true
        network_mode: host
        cap_add:
            - NET_ADMIN
        container_name: pulseaudio
        hostname: pulseaudio
