# Describes the format for available hasl services

clear_cache:
  description: Clears all cached data and forces API data retreival on next sensor refresh

find_location:
  description: Searches for a SL location id using a freetext string
  fields:
    search_string:
      description: Enter the location to find id
      example: 'Slussen'

find_trip_id:
   description: Search for a trip between two places using either SL orgigin and destination locations
   fields:
     org:
       description: The origin for the trip
       example: 4243
     dest:
       description: The destination for the trip
       example: 2412

find_trip_pos:
   description: Search for a trip between two placings using longitude and latitude
   fields:
     orig_lat:
       description: The origin location for the trip
       example: '20.20'
     orig_long:
       description: The origin location for the trip
       example: '10.20'
     dest_lat:
       description: The destination location for the trip
       example: '20.20'
     dest_long:
       description: The destination location for the trip
       example: '10.20'
       