version: '2'
services:
    warrior:
        image: archiveteam/warrior-dockerfile
        volumes:
            - "/media/saga/Media/Containers/warrior/data:/data/data"
        ports:
          - "8001:8001"
        env_file: ./settings.env
        restart: always
        privileged: true
        container_name: warrior
