version: '2'
services:
    plex:
        image: lsioarmhf/plex
        volumes:
            - "/media/data/TV:/data/TV"
            - "/media/data/Music:/data/Music"
            - "/media/data/Films:/data/Films"
            - "/media/data/Containers/plex/transcode:/transcode"
            - "/media/data/Containers/plex/config:/config"
        environment:
            - PUID=1001
            - PGID=1001
        network_mode: "host"
        restart: always
        container_name: plex
        mem_limit: 416m
