version: '2'
services:
    plex:
        image: linuxserver/plex:arm32v7-latest
        volumes:
            - "/media/data/Music:/data/Music"
            - "/media/data/Containers/plex/transcode:/transcode"
            - "/media/data/Containers/plex/config:/config"
        environment:
            - PUID=1001
            - PGID=1001
        network_mode: "host"
        restart: always
        container_name: plex
        mem_limit: 1000m
