version: '2'
services:
    n8n:
        image: n8nio/n8n
        volumes:
            - "/media/saga/Media/Containers/n8n/config:/home/node/.n8n"
        ports:
            - "5678:5678"
        restart: always
        container_name: n8n
        #command: "n8n start --tunnel"
