version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: ./settings.env
    container_name: miniflux
    restart: always
  db:
    image: postgres:latest
    env_file: ./settings.env
    volumes:
      - /media/saga/Media/Containers/miniflux/db/:/var/lib/postgresql/data
    container_name: miniflux_db
    restart: always
