homeassistant:
  name: Sycamore
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# API
api:

# Python Scripts
python_script:

# Server Config
http:
  base_url: !secret base_url
  # server_host: sycamore.lan

# Lovelace
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js?v=1.2.0
      type: module
    - url: /browser_mod.js
      type: module
    - url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.6.0
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
    - url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
  dashboards:
    lovelace-tablet:
      mode: yaml
      filename: ui-tablet.yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: false
      require_admin: true

# Asus
asuswrt:
  host: !secret asus_ip
  mode: router
  protocol: ssh
  username: !secret asus_username
  password: !secret asus_password

# Google
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# Xiaomi vacuum
vacuum:
  - platform: xiaomi_miio
    host: !secret monk_ip
    token: !secret monk_token

# Xiaomi fan
fan:
  - platform: xiaomi_miio_fan
    name: Fan
    host: !secret fan_ip
    token: !secret fan_token

# UPnP
upnp:

# tplink
# tplink:

# Cloud
# cloud:

# WOL
wake_on_lan:

# Allows you to issue voice commands from the frontend
conversation:

# Lightning
wwlln:

# DuckDNS
duckdns:
  domain: !secret duck_domain
  access_token: !secret duck_access_token

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - person.scott
      - person.gemma

      - calendar.washing

      - binary_sensor.blink_front_motion_detected
      - binary_sensor.blink_front_camera_armed
      - sensor.blink_front_battery

      - binary_sensor.blink_back_motion_detected
      - binary_sensor.blink_back_camera_armed
      - sensor.blink_back_battery

      - binary_sensor.blink_indoor_front_motion_detected
      - binary_sensor.blink_indoor_front_camera_armed
      - sensor.blink_indoor_front_battery

      - binary_sensor.blink_indoor_back_motion_detected
      - binary_sensor.blink_indoor_back_camera_armed
      - sensor.blink_indoor_back_battery

      - weather.dark_sky
      - sun.sun
      - sensor.moon
      - sensor.u_s_air_pollution_level
      - sensor.u_s_main_pollutant

      - media_player.luther_universal_tv

      - sensor.ip_address

      - light.lounge_light_tall
      - light.hallway
      - light.lounge_light_small
      - switch.cloud

      - switch.dockermon_blinkt
      - switch.dockermon_nodered
      - switch.dockermon_plex
      - switch.dockermon_plex_oak
      - switch.dockermon_warrior
      - switch.dockermon_watchtower_oak
      - switch.dockermon_watchtower
      - switch.dockermon_f_h

      - binary_sensor.post
      - input_boolean.post_visibility

      - sensor.u_s_air_quality_index
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_temperature

      - sensor.battery_level_post
      - sensor.lounge_switch_battery_level
      - sensor.tradfri_motion_sensor_battery_level
      - sensor.fp3_battery_level
      - sensor.cpu_use_mycroft
      - sensor.load_5m
      - sensor.cpu_temperature
      - sensor.cpu_temperature_mycroft
      - sensor.ram_use_mycroft
      - sensor.memory_use_percent

      - sensor.indoor_temperature

      - vacuum.xiaomi_vacuum_cleaner
      - fan.fan

      - sensor.steam_76561197969853112

# Recorder
recorder:
  purge_keep_days: 3

# Discover some devices automatically
discovery:
  # ignore:
  #  - plex_mediaserver

mobile_app:

# System Health
system_health:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.weather_summary_automation
      - sensor.since_last_boot_sycamore
      - sensor.since_last_boot_mycroft
      - sensor.date
      - sensor.time
      - sensor.scott_last_changed
      - sensor.gemma_last_changed
      - sensor.scott_last_changed_h
      - sensor.gemma_last_changed_h

# Customise Logger
logger:
  default: info
  logs:
    homeassistant.helpers.entity: critical
    homeassistant.components.plex.media_player: error

# Enables the frontend
frontend:
  themes: !include themes.yaml


# Map
map:

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

#  Image Processing
#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.blink_front
#      - entity_id: camera.blink_back
#      - entity_id: camera.blink_indoor_front
#      - entity_id: camera.blink_indoor_back


# Track the sun
sun:

# Enable the configurator
config:

# Checks for available updates
updater:

# Emulate Hue for Echo
emulated_hue:
  exposed_domains:
    - switch
    - light
    - input_boolean
    - fan
    - group

# LIFX
# lifx:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Zeroconf
zeroconf:

# Zones
# zone:
#   - name: Home
#     latitude: !secret latitude
#     longitude: !secret longitude
#     radius: 100
#     icon: mdi:home-map-marker

# Text to Speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group
      - !secret telegram_scottsweb
      - !secret telegram_gemma

# Speedtest
speedtestdotnet:
  scan_interval:
    days: 1
  monitored_conditions:
    - ping
    - download
    - upload

# MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant

mqtt_statestream:
  base_topic: homeassistant

# Mycroft
mycroft:
  host: !secret mycroft_ip

# Browser Mod
browser_mod:
  prefix: "browser_"
  devices:
    f2f7f59f-59355108:
      name: arnott
    fc0145b0_c697cef7:
      name: wilson
  disable:
    - all

# Timers
timer:
  washing:
    duration: '01:00:00'
    icon: 'mdi:washing-machine'

# persons
person: !include persons.yaml

# Sensors
sensor: !include_dir_list sensors

binary_sensor:
  - platform: iss
    show_on_map: false
    scan_interval: 300

# Utility Meters
# utility_meter: !include utilities.yaml

# Device Tracking
device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Switches
switch: !include switches.yaml

# Scripts
script: !include scripts.yaml

# Rest Commands
rest_command: !include rest-commands.yaml

# Controls
input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml
#input_text : !include input-text.yaml
input_boolean: !include input-booleans.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations

# Scenes
scene: !include_dir_list scenes

# Notifcations
notify: !include notifications.yaml

# Shell Commands
shell_command: !include shell_commands.yaml
