homeassistant:
  name: Sycamore
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 50
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# Server Config
http:
  base_url: !secret base_url
  # server_host: sycamore.lan

# Lovelace
lovelace:
  mode: yaml

# Asus
asuswrt:
  host: !secret asus_ip
  mode: router
  protocol: ssh
  username: !secret asus_username
  password: !secret asus_password

# Google
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# tplink
# tplink:

# Cloud
# cloud:

# WOL
wake_on_lan:

# Allows you to issue voice commands from the frontend
conversation:

# Lightning
wwlln:

# DuckDNS
duckdns:
  domain: !secret duck_domain
  access_token: !secret duck_access_token

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - automation
      - script
      - input_text
      - input_number
    entities:
      - binary_sensor.iss
      - sensor.since_last_boot_sycamore
      - sensor.since_last_boot_mycroft
      - persistent_notification.httplogin
      - persistent_notification.config_entry_discovery
      - persistent_notification.python_version
      - binary_sensor.blink_back_motion_enabled
      - binary_sensor.blink_front_motion_enabled
      - binary_sensor.blink_indoor_front_motion_enabled
      - binary_sensor.blink_indoor_back_motion_enabled
      - sensor.blink_front_notifications
      - sensor.blink_back_notifications
      - sensor.blink_indoor_front_notifications
      - sensor.blink_indoor_back_notifications
      - camera.blink_front
      - camera.blink_back
      - camera.blink_indoor_front
      - camera.blink_indoor_back
      - sensor.blink_back_temperature
      - sensor.blink_front_temperature
      - sensor.blink_indoor_front_temperature
      - sensor.blink_indoor_back_temperature
      - sensor.blink_back_wifi_signal
      - sensor.blink_front_wifi_signal
      - sensor.blink_indoor_back_wifi_signal
      - sensor.blink_indoor_front_wifi_signal
      - switch.tv_ir
      - media_player.plex_web_chrome
      - media_player.luther_audio
      - media_player.luther_audio_2
      - media_player.aftt
      - media_player.luther
      - media_player.luther_2
      - media_player.tv_firetv
      - media_player.tv_kodi
      - media_player.this_device
      - media_player.dot
      - switch.tv_mute
      - sensor.plex
      - sensor.asuswrt_download
      - sensor.asuswrt_download_speed
      - sensor.asuswrt_upload
      - sensor.asuswrt_upload_speed
      - alarm_control_panel.blink_sync
      - sensor.last_blocked_call
      - plant.flora_front_plant
      - plant.flora_back_plant
      - switch.game_core
      - media_player.plex_firefox_2
      - media_player.this_device_2
      - media_player.this_device
      - media_player.arnott
      - sensor.daily_energy
      - sensor.monthly_energy
      - sensor.gbp_sek
      - sensor.sek_gbp
      - sensor.time
      - sensor.date
      - sensor.wilson
      - media_player.wilson
      - light.wilson
      - sensor.arnott
      - media_player.arnott
      - light.arnott

# Recorder
recorder:
  purge_interval: 2
  purge_keep_days: 2

# Discover some devices automatically
discovery:
  # ignore:
  #  - plex_mediaserver

mobile_app:

# System Health
system_health:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.weather_summary_automation
      - sensor.since_last_boot_sycamore
      - sensor.since_last_boot_mycroft
      - sensor.date
      - sensor.time

# Customise Logger
logger:
  default: info
  logs:
    homeassistant.helpers.entity: critical
    homeassistant.components.plex.media_player: error

# Enables the frontend
frontend:
  themes: !include themes.yaml


# Map
map:

# Weather
weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

#  Image Processing
#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.blink_front
#      - entity_id: camera.blink_back
#      - entity_id: camera.blink_indoor_front
#      - entity_id: camera.blink_indoor_back

# Plants
plant:
  flora_back_plant:
    sensors:
      moisture: sensor.flora_back_moisture
      battery: sensor.flora_back_battery
      temperature: sensor.flora_back_temperature
      conductivity: sensor.flora_back_conductivity
      brightness: sensor.flora_back_light_intensity
    min_moisture: 20
  flora_front_plant:
    sensors:
      moisture: sensor.flora_front_moisture
      battery: sensor.flora_front_battery
      temperature: sensor.flora_front_temperature
      conductivity: sensor.flora_front_conductivity
      brightness: sensor.flora_front_light_intensity
    min_moisture: 20

# Track the sun
sun:

# Enable the configurator
config:

# Checks for available updates
updater:

# Emulate Hue for Echo
emulated_hue:
  exposed_domains:
    - switch
    - light
    - input_boolean
    - fan
    - group

# LIFX
# lifx:

# IFTTT
ifttt:
  key: !secret ifttt_key

# blink
blink:
  username: !secret blink_username
  password: !secret blink_password

# Zeroconf
zeroconf:

# Zones
# zone:
#   - name: Home
#     latitude: !secret latitude
#     longitude: !secret longitude
#     radius: 100
#     icon: mdi:home-map-marker

# Text to Speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group
      - !secret telegram_scottsweb
      - !secret telegram_gemma

# Speedtest
speedtestdotnet:
  scan_interval:
    days: 1
  monitored_conditions:
    - ping
    - download
    - upload

# MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant

mqtt_statestream:
  base_topic: homeassistant

# Mycroft
mycroft:
  host: !secret mycroft_ip

# Plex
plex:
  host: !secret plex_server_ip
  token: !secret plex_token
  server: oak

# Browser Mod
browser_mod:
  prefix: "browser_"
  devices:
    08adfc81-9c485d86:
      name: arnott
    f8632809_a3647f84:
      name: wilson
  disable:
    - all

# persons
person: !include persons.yaml

# Sensors
sensor: !include_dir_list sensors

binary_sensor:
  - platform: iss
    show_on_map: false
    scan_interval: 300

# Utility Meters
utility_meter: !include utilities.yaml

# Device Tracking
device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Switches
switch: !include switches.yaml

# Scripts
script: !include scripts.yaml

# Rest Commands
rest_command: !include rest-commands.yaml

# Controls
# input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml
#input_text : !include input-text.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations

# Scenes
scene: !include_dir_list scenes

# Notifcations
notify: !include notifications.yaml

# Shell Commands
shell_command: !include shell_commands.yaml
