homeassistant:
  name: Lagom
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 15
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# API
api:

# Python Scripts
python_script:

# Server Config
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.11.5
    - 192.168.128.0/24
    - 172.26.0.0/24

# Lovelace
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
      type: js
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: js
#  dashboards:
#    lovelace-tablet:
#      mode: yaml
#      filename: ui-tablet.yaml
#      title: Tablet
#      icon: mdi:tablet
#      show_in_sidebar: false
#      require_admin: true

# Xiaomi fan
fan:
  - platform: xiaomi_miio_fan
    name: Fan
    host: !secret fan_ip
    token: !secret fan_token

# Cloud
# cloud:

# Docker
monitor_docker:
  - name: Docker
    containers:
      - deconz
      - pihole
      - watchtower
      - plex
      - folding
      - warrior
      - nodered
      - homeassistant
      - esphome
      - caddy
      - miniflux
      - jottacloud
      - wireguard
      - syncthing
      - appdaemon
    rename:
      deconz: deCONZ
      pihole: "Pi-Hole"
      watchtower: Watchtower
      plex: Plex
      folding: "F@H"
      warrior: Warrior
      mosquitto: MQTT
      nodered: "Node-RED"
      homeassistant: "Home Assistant"
      esphome: ESPHome
      caddy: Caddy
      miniflux: Miniflux
      jottacloud: Jottacloud
      wireguard: Wireguard
      syncthing: Syncthing
      appdaemon: "AppDaemon"
    monitored_conditions:
      - containers_running
      - containers_total
      - state
      - memory
      - containers_memory
      - containers_memory_percentage
      - cpu_percentage
      - containers_cpu_percentage

# WOL
wake_on_lan:

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - person.scott
      - person.gemma

      - alarm_control_panel.blink_sycamore

      - binary_sensor.blink_front_door_motion_detected
      - binary_sensor.blink_front_door_camera_armed
      - binary_sensor.blink_front_door_battery

      - binary_sensor.blink_kitchen_motion_detected
      - binary_sensor.blink_kitchen_camera_armed
      - binary_sensor.blink_kitchen_battery

      - binary_sensor.blink_street_motion_detected
      - binary_sensor.blink_street_camera_armed
      - binary_sensor.blink_street_battery

      - weather.home
      - sun.sun
      - sensor.moon
      - sensor.u_s_air_pollution_level
      - sensor.u_s_main_pollutant

      - media_player.tv

      - sensor.ip_address

      - light.lounge_light_tall
      - light.hallway
      - light.lounge_light_small
      - switch.cloud
      - light.nanoleaf
      - light.cameras
      - light.cabinet_1
      - light.cabinet_2

      - switch.docker_caddy
      - switch.docker_deconz
      - switch.docker_folding
      - switch.docker_jottacloud
      - switch.docker_miniflux
      - switch.docker_wireguard
      - switch.docker_pihole
      - switch.docker_plex
      - switch.docker_synchthing
      - switch.docker_warrior
      - switch.docker_watchtower
      - switch.docker_appdaemon

      - binary_sensor.post
      - input_boolean.post_visibility

      - sensor.u_s_air_quality_index

      - sensor.battery_level_post
      - sensor.lounge_switch_battery_level
      - sensor.tradfri_motion_sensor_battery_level
      - sensor.fp3_battery_level
      - sensor.load_5m
      - sensor.cpu_temperature
      - sensor.cpu_temperature_mycroft
      - sensor.memory_use_percent
      - sensor.bedroom_temperature

      - sensor.indoor_temperature

      - vacuum.xiaomi_vacuum_cleaner
      - fan.fan

      - sensor.steam_76561197969853112

      - binary_sensor.water_sensor_bathroom
      - binary_sensor.water_sensor_kitchen

      - binary_sensor.hallway

      - switch.do_not_disturb
      - switch.presence_emulator

      - sensor.solar_host

# Recorder
recorder:
  purge_keep_days: 3

# Discover some devices automatically
discovery:

# Mobile App support
mobile_app:

# System Health
system_health:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.weather_summary_automation
      - sensor.since_last_boot
      - sensor.date
      - sensor.time
      - sensor.scott_last_changed
      - sensor.gemma_last_changed
      - sensor.scott_last_changed_h
      - sensor.gemma_last_changed_h

# Customise Logger
logger:
  default: info
  logs:
    homeassistant.helpers.entity: critical
    homeassistant.components.plex.media_player: error

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Map
# map:

# Shopping list
shopping_list:

#  Image Processing
#image_processing:
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.blink_front
#      - entity_id: camera.blink_back
#      - entity_id: camera.blink_indoor_front
#      - entity_id: camera.blink_indoor_back

# Track the sun
sun:

# Enable the configurator
config:

# Emulate Hue for Echo
emulated_hue:
  exposed_domains:
    - switch
    - light
    - input_boolean
    - fan
    - group

# LIFX
# lifx:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Zeroconf
zeroconf:

# Text to Speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Telegram
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group_swengland
      - !secret telegram_group_family
      - !secret telegram_scottsweb
      - !secret telegram_gemma

# MQTT
#mqtt:
#  broker: !secret mqtt_ip
#  port: 1883
# client_id: home-assistant

#mqtt_statestream:
#  base_topic: homeassistant

# Lametric
lametric:
  client_id: !secret lametric_id
  client_secret: !secret lametric_secret

# Timers
timer:
  washing:
    duration: '01:00:00'
    icon: 'mdi:washing-machine'

# Sensors
sensor: !include_dir_list sensors

# Utility Meters
# utility_meter: !include utilities.yaml

# Device Tracking
# device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Switches
switch: !include switches.yaml

# MQTT switches
mqtt: !include mqtt.yaml

# Scripts
script: !include scripts.yaml

# Rest Commands
rest_command: !include rest-commands.yaml

# Controls
#input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml
#input_text : !include input-text.yaml
input_boolean: !include input-booleans.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations

# Scenes
scene: !include_dir_list scenes

# Notifcations
notify: !include notifications.yaml

# Shell Commands
shell_command: !include shell_commands.yaml
