homeassistant:
  name: Sycamore
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 94
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# Server Config
http:
  api_password: !secret api_password
  # server_host: sycamore.lan
  trusted_networks:
    - 192.168.11.0/24
    #- 127.0.0.1
    #- ::1

# Lovelace
lovelace:
  mode: yaml

# Asus
asuswrt:
  host: !secret asus_ip
  mode: router
  protocol: ssh
  username: !secret asus_username
  password: !secret asus_password

# Cloud
# cloud:

# Allows you to issue voice commands from the frontend
conversation:

# DuckDNS
duckdns:
  domain: !secret duck_domain
  access_token: !secret duck_access_token

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - automation
      - script
      - input_text
      - input_number
    entities:
      - binary_sensor.hallway_thermostat_is_using_emergency_heat
      - binary_sensor.hallway_thermostat_is_locked
      - binary_sensor.upstairs_nest_protect_online
      - binary_sensor.downstairs_nest_protect_online
      - binary_sensor.hallway_thermostat_fan
      - binary_sensor.iss
      - sensor.hallway_thermostat_hvac_state
      - binary_sensor.hallway_thermostat_has_leaf
      - binary_sensor.hallway_thermostat_online
      - sensor.since_last_boot_sycamore
      - sensor.since_last_boot_willow
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_percentage_blocked_today
      - media_player.aquaris_x5_plus
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_domains_blocked
      - persistent_notification.httplogin
      - sensor.next_train_status
      - sensor.next_train_to_wat
      - sensor.next_trains_estimated
      - sensor.next_trains_origin
      - sensor.next_trains_platform
      - sensor.next_trains_scheduled
      - binary_sensor.blink_back_motion_enabled
      - binary_sensor.blink_front_motion_enabled
      - binary_sensor.blink_indoor_front_motion_enabled
      - binary_sensor.blink_indoor_back_motion_enabled
      - sensor.blink_front_notifications
      - sensor.blink_back_notifications
      - sensor.blink_indoor_front_notifications
      - sensor.blink_indoor_back_notifications
      - camera.blink_front
      - camera.blink_back
      - camera.blink_indoor_front
      - camera.blink_indoor_back
      - sensor.blink_back_temperature
      - sensor.blink_front_temperature
      - sensor.blink_indoor_front_temperature
      - sensor.blink_indoor_back_temperature
      - sensor.blink_back_wifi_signal
      - sensor.blink_front_wifi_signal
      - sensor.blink_indoor_back_wifi_signal
      - sensor.blink_indoor_front_wifi_signal
      - switch.tv_ir
      - media_player.plex_web_chrome
      - media_player.pixel_2
      - media_player.luther_audio
      - media_player.luther_audio_2
      - media_player.aftt
      - media_player.luther
      - media_player.luther_2
      - media_player.tv_firetv
      - media_player.tv_kodi
      - media_player.scotts_alexa_apps
      - media_player.this_device
      - media_player.dot
      - switch.tv_mute
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_blocked_today_2
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_ads_percentage_blocked_today_2
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_cached_2
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_forwarded_2
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_queries_today_2
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_unique_clients_2
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_dns_unique_domains_2
      - sensor.pihole_domains_blocked
      - sensor.pihole_domains_blocked_2
      - sensor.plex
      - sensor.sycamore_eta
      - sensor.upstairs_nest_protect_color_status
      - sensor.downstairs_nest_protect_color_status
      - sensor.asuswrt_download
      - sensor.asuswrt_download_speed
      - sensor.asuswrt_upload
      - sensor.asuswrt_upload_speed
      - alarm_control_panel.blink_sync

# Recorder
recorder:
  purge_interval: 2
  purge_keep_days: 2

# Discover some devices automatically
discovery:
  # ignore:
  #  - plex_mediaserver

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.nest_summary_automation
      - automation.weather_summary_automation
      - sensor.since_last_boot_sycamore
      - sensor.since_last_boot_willow
      - sensor.next_trains_estimated
      - sensor.next_trains_origin
      - sensor.next_trains_scheduled

# Customise Logger
logger:
  default: info
  logs:
    homeassistant.components.sensor.plex: error

# Enables the frontend
frontend:
  themes:
    sycamore:
      primary-color: "#a8122b"
      label-badge-red: "#a8122b"
      paper-item-icon-color: "#747474"
      paper-item-icon-active-color: "#FDD835"
      paper-toggle-button-checked-ink-color: "#a8122b"
      paper-toggle-button-checked-button-color: "#a8122b"
      paper-toggle-button-checked-bar-color: "#a8122b"
      accent-color: "#21aedd"

# Map
map:

# Track the sun
sun:

# Enable the configurator
config:

# Checks for available updates
updater:

# Emulate Hue for Echo
emulated_hue:
  exposed_domains:
    - switch
    - light
    - input_boolean
    - fan
    - group

# LIFX
lifx:

# IFTTT
ifttt:
  key: !secret ifttt_key

# blink
blink:
  username: !secret blink_username
  password: !secret blink_password
  scan_interval: 60

# Zeroconf
zeroconf:

# Zones
zone sycamore:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:home-map-marker

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  structure:
    - Sycamore

climate:
  platform: nest

# Text to Speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_group
      - !secret telegram_scottsweb
      - !secret telegram_gemma

# MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant

mqtt_statestream:
  base_topic: homeassistant

# Mycroft
mycroft:
  host: !secret mycroft_ip

# Sensors
sensor: !include_dir_list sensors

binary_sensor:
  - platform: iss
    show_on_map: true

# Device Tracking
device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Switches
switch: !include switches.yaml

# Scripts
script: !include scripts.yaml

# Rest Commands
rest_command: !include rest-commands.yaml

# Controls
# input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml
#input_text : !include input-text.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations

# Scenes
scene: !include_dir_list scenes

# Notifcations
notify: !include notifications.yaml

# Shell Commands
shell_command: !include shell_commands.yaml
