homeassistant:
  name: Sycamore
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 94
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customisations.yaml

# Server Config
http:
  api_password: !secret api_password
  # server_host: sycamore.lan
  trusted_networks:
    - 192.168.11.0/24
    #- 127.0.0.1
    #- ::1

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - automation
    # entities:
      # - sensor.last_boot
      # - sensor.date

# Recorder
recorder:
  purge_days: 14

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Track the sun
sun:

# Checks for available updates
updater:

# Emulate Hue for Echo
emulated_hue:

# LIFX
light:
  platform: lifx

# IFTTT
ifttt:
  key: !secret ifttt_key

# Zeroconf
zeroconf:

# Zones
zone sycamore:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:home-map-marker

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

# Zwave
zwave:
  usb_path: /zwaveusbstick

# MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant

# Sensors
sensor: !include_dir_list sensors

# Device Tracking
device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Controls
# input_select: !include input-selects.yaml
# input_slider: !include input-sliders.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations
