homeassistant:
  name: Sycamore
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 94
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml

# Server Config
http:
  api_password: !secret api_password
  # server_host: sycamore.lan
  trusted_networks:
    - 192.168.11.0/24
    #- 127.0.0.1
    #- ::1

# Allows you to issue voice commands from the frontend
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - automation
    entities:
      - binary_sensor.hallway_thermostat_is_using_emergency_heat
      - binary_sensor.hallway_thermostat_is_locked
      - binary_sensor.upstairs_nest_protect_online
      - binary_sensor.downstairs_nest_protect_online
      - binary_sensor.hallway_thermostat_fan
      - binary_sensor.iss
      - sensor.hallway_thermostat_hvac_state
      - binary_sensor.hallway_thermostat_has_leaf
      - binary_sensor.hallway_thermostat_online
      - sensor.since_last_boot
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_percentage_blocked_today
      - media_player.aquaris_x5_plus
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_unique_clients
      - sensor.pihole_dns_unique_domains
      - sensor.pihole_domains_blocked
      - persistent_notification.httplogin
      - sensor.next_train_status
      - sensor.next_train_to_wat
      - sensor.next_trains_estimated
      - sensor.next_trains_origin
      - sensor.next_trains_platform
      - sensor.next_trains_scheduled
      - binary_sensor.blink_back_motion_enabled
      - binary_sensor.blink_front_motion_enabled
      - sensor.blink_front_notifications
      - sensor.blink_back_notifications
      - script.blink_back_capture_script
      - script.blink_front_capture_script
      - camera.front
      - camera.back

# Recorder
recorder:
  purge_interval: 7
  purge_keep_days: 14

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - automation.nest_summary_automation
      - automation.weather_summary_automation

# Enables the frontend
frontend:
  themes:
    sycamore:
      primary-color: "#a8122b" 
      label-badge-red: "#a8122b"
      paper-item-icon-color: "#747474"
      paper-item-icon-active-color: "#FDD835"
      paper-toggle-button-checked-ink-color: "#a8122b"
      paper-toggle-button-checked-button-color: "#a8122b"
      paper-toggle-button-checked-bar-color: "#a8122b"

# Map
map:

# Track the sun
sun:

# Enable the configurator
config:

# Checks for available updates
updater:

# Emulate Hue for Echo
emulated_hue:

# LIFX
light:
  platform: lifx

# IFTTT
ifttt:
  key: !secret ifttt_key
  
# blink
blink:
  username: !secret blink_username
  password: !secret blink_password

# Zeroconf
zeroconf:

# Zones
zone sycamore:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:home-map-marker

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

climate:
  platform: nest

# Zwave
#zwave:
#  usb_path: /zwaveusbstick

# MQTT
mqtt:
  broker: !secret mqtt_ip
  port: 1883
  client_id: home-assistant

mqtt_statestream:
  base_topic: homeassistant

# Sensors
sensor: !include_dir_list sensors

binary_sensor:
  - platform: iss
    show_on_map: true

# Device Tracking
device_tracker: !include device-tracker.yaml

# Media Players
media_player: !include media-player.yaml

# Switches
switch: !include switches.yaml

# Scripts
script: !include scripts.yaml

# Controls
# input_select: !include input-selects.yaml
# input_slider: !include input-sliders.yaml

# Groups and Other UIs
group: !include groups.yaml
panel_iframe: !include panels-iframe.yaml

# Automations
automation: !include_dir_list automations

# Scenes
scene: !include_dir_list scenes

# Notifcations
notify: !include notifications.yaml
