version: '2'
services:
    homeassistant:
        image: lroguet/rpi-home-assistant
        volumes:
            - "/home/pilot/.ssh:/root/.ssh:ro"
            - "/mnt/data/Containers/homeassistant:/config"
            - "/etc/localtime:/etc/localtime:ro"
            - "/mnt/data/Containers/ncid/cidcall.log:/var/log/cidcall.log"
        network_mode: "host"
        restart: always
        container_name: homeassistant
