- platform: kodi
  host: !secret kodi_ip
  port: 8080
  name: TV Kodi

#- platform: androidtv
#  adbkey: "/config/android/adbkey"
#  name: 'TV FireTV'
#  host: !secret tv_ip

- platform: universal
  name: 'TV'
  children:
    - media_player.tv_kodi # kodi
    - media_player.plex_for_kodi # plex

#   commands:
#     turn_on:
#       service: switch.turn_on
#       data:
#         entity_id: switch.tv
#     turn_off:
#       service: switch.turn_off
#       data:
#         entity_id: switch.tv
#     volume_up:
#       service: script.tv_vol_up
#     volume_down:
#       service: script.tv_vol_down
#     volume_mute:
#       service: switch.turn_on
#       data:
#         entity_id: switch.tv_mute
#   attributes:
#     state: switch.tv
#     is_volume_muted: switch.tv_mute
