- platform: kodi
  host: !secret kodi_ip
  port: 8080
  name: TV Kodi

#- platform: androidtv
#  adbkey: "/config/android/adbkey"
#  name: 'TV FireTV'
#  host: !secret tv_ip

- platform: universal
  name: 'TV'
  children:
    - media_player.tv_kodi # kodi
    - media_player.plex_for_kodi # plex


- platform: linkplay
  host: !secret teeger_ip
  name: teeger
  sources:
    {
      'line-in': 'TV Sound',
      'bluetooth': 'Bluetooth',
      'https://sverigesradio.se/topsy/direkt/132-hi-aac.m3u ': 'P1',
      'https://sverigesradio.se/topsy/direkt/2562-hi-aac.m3u': 'P2',
      'https://sverigesradio.se/topsy/direkt/164-hi-aac.m3u': 'P3',
      'https://sverigesradio.se/topsy/direkt/701-hi-aac.m3u': 'P4 Stockholm',
    }

#   commands:
#     turn_on:
#       service: switch.turn_on
#       data:
#         entity_id: switch.tv
#     turn_off:
#       service: switch.turn_off
#       data:
#         entity_id: switch.tv
#     volume_up:
#       service: script.tv_vol_up
#     volume_down:
#       service: script.tv_vol_down
#     volume_mute:
#       service: switch.turn_on
#       data:
#         entity_id: switch.tv_mute
#   attributes:
#     state: switch.tv
#     is_volume_muted: switch.tv_mute
