- platform: kodi
  host: !secret kodi_ip
  port: 8080
  name: TV Kodi
  user: kodi
- platform: cast

# Media Center
#platform: universal
  #name: Lounge
  #children:
    #- media_player.goody
    #- media_player.goody_kodi
