- platform: kodi
  host: !secret kodi_ip
  port: 8080
  name: TV Kodi
  user: kodi

- platform: cast

- platform: firetv
  device: luther
  name: 'TV FireTV'
  
- platform: plex
  scan_interval: 4
 
- platform: universal
  name: 'Luther Universal (TV)'
  children:
    - media_player.tv_kodi # kodi
    - media_player.aftt # plex
    - media_player.tv_firetv # firetv (via server)
    - media_player.luther # chromecast (app)
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.tv
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.tv
    volume_up:
      service: script.tv_vol_up
    volume_down:
      service: script.tv_vol_down
    volume_mute:
      service: switch.turn_on
      data:
        entity_id: switch.tv_mute
  attributes:
    state: switch.tv
    is_volume_muted: switch.tv_mute

- platform: universal
  name: 'Luther Universal (Audio)'
  children:
    - media_player.luther_audio
    - media_player.luther_audio_2
    