plex:
  title: 'Plex'
  icon: 'mdi:plex'
  url: !secret plex_ui_ip
#nodered:
#  title: 'Node-RED'
#  icon: 'mdi:vector-polyline'
#  url: !secret node_red_ip
pihole_sycamore:
  title: 'Pi-hole'
  icon: 'mdi:checkbox-blank-circle'
  url: 'http://pihole.saga.lan/admin/'
miniflux:
  title: 'RSS'
  icon: 'mdi:rss-box'
  url: !secret miniflux_url
warrior:
  title: 'Warrior'
  icon: 'mdi:archive'
  url: !secret warrior_url
deconz:
  title: 'Deconz'
  icon: 'mdi:zigbee'
  url: !secret deconz_url
esphome:
  title: ESPHome
  icon: 'mdi:chip'
  url: !secret esphome_url
storj:
  title: Storj
  icon: 'mdi:nas'
  url: !secret storj_url
syncthing:
  title: Syncthing
  icon: 'mdi:sync-circle'
  url: !secret syncthing_url
helium:
  title: Helium
  icon: 'mdi:radio-tower'
  url: !secret helium_url
router:
  title: Router
  icon: 'mdi:router-wireless'
  url: !secret router_url
n8n:
  title: n8n
  icon: 'mdi:transit-connection-variant'
  url: !secret n8n_url
meshtastic:
  title: Meshtastic
  icon: 'mdi:access-point-network'
  url: !secret meshtastic_url
