kodi:
  title: 'Kodi'
  icon: 'mdi:music-box-multiple'
  url: !secret kodi_ui_ip
plex:
  title: 'Plex'
  icon: 'mdi:plex'
  url: !secret plex_ui_ip
nodered:
  title: 'Node-RED'
  icon: 'mdi:vector-polyline'
  url: !secret node_red_ip
pihole_sycamore:
  title: 'Pi-hole (Bonsai)'
  icon: 'mdi:checkbox-blank-circle'
  url: 'http://pihole.sycamore.lan/admin/'
pihole_mycroft:
  title: 'Pi-hole (Mycroft)'
  icon: 'mdi:checkbox-blank-circle'
  url: 'http://pihole.mycroft.lan/admin/'
miniflux:
  title: 'RSS'
  icon: 'mdi:rss-box'
  url: !secret miniflux_url
warrior:
  title: 'Warrior'
  icon: 'mdi:archive'
  url: !secret warrior_url
wiki:
  title: 'Wiki'
  icon: 'mdi:note'
  url: !secret wiki_url
deconz:
  title: 'Deconz'
  icon: 'mdi:usb-flash-drive'
  url: !secret deconz_url
folding:
  title: F@H
  icon: 'mdi:pill'
  url: !secret folding_url
esphome:
  title: ESPHome
  icon: 'mdi:chip'
  url: !secret esphome_url
