- platform: tplink
  host: !secret tplink_switch_1
  name: "Lounge Light Tall"

- platform: tplink
  host: !secret tplink_switch_2
  name: "Lounge Light Small"

- platform: tplink
  host: !secret tplink_switch_3
  name: "Bedroom Light"
  
- platform: command_line
  switches:
    pihole_switch:
      command_on: !secret pihole_command_on
      command_off: !secret pihole_command_off
      command_state: !secret pihole_command_state
      value_template: "{{ value_json.status == 'enabled' }}"