- platform: command_line
  switches:
    vpn_liskeard_switch:
      command_on: !secret ssh_liskeard_vpn_on
      command_off: !secret ssh_liskeard_vpn_off
      command_state: !secret ssh_liskeard_vpn_status
      value_template: >
        {{ "vpn" in value }}

- platform: command_line
  switches:
    vpn_ee_switch:
      command_on: !secret ssh_ee_vpn_on
      command_off: !secret ssh_ee_vpn_off
      command_state: !secret ssh_ee_vpn_status
      value_template: >
        {{ "vpn" in value }}

- platform: mqtt
  name: "Presence Emulator"
  state_topic: "sycamore/presence/switch"
  command_topic: "sycamore/presence/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Do Not Disturb"
  state_topic: "sycamore/dnd/switch"
  command_topic: "sycamore/dnd/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Auto Fan"
  state_topic: "sycamore/fan/switch"
  command_topic: "sycamore/fan/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
