custom_header:
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        kiosk_mode: false
    - conditions:
        query_string: kiosk
      config:
        kiosk_mode: true
preload_cards:
  - markdown
  - conditional
  - map
  - entities
  - iframe

title: Sycamore
views:
# Home
  - title: Home
    icon: mdi:home
    path: default_view
    badges:
      - person.gemma
      - person.scott
    cards:
      - type: entities
        title: Exchange Rates
        show_header_toggle: false
        entities:
          - sensor.gbp_sek
          - sensor.sek_gbp
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.lounge_light_tall
          - light.lounge_light_small
          - light.hallway
          - switch.cloud
      - type: sensor
        entity: sensor.indoor_temperature
        graph: line
      - type: entities
        title: Fan
        entities:
          - fan.fan
          - switch.auto_fan
      - type: entities
        title: Coronavirus Sweden
        show_header_toggle: false
        entities:
          - sensor.sweden_coronavirus_confirmed
          - sensor.sweden_coronavirus_current
          - sensor.sweden_coronavirus_deaths
          - sensor.sweden_coronavirus_recovered
      - type: 'custom:vacuum-card'
        entity: vacuum.xiaomi_vacuum_cleaner
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors

#      - type: entities
#        title: Coins
#        show_header_toggle: false
#        entities:
#          - sensor.bitcoin
#          - sensor.bitcoin_cash
#          - sensor.ethereum
#          - sensor.ripple
#          - sensor.litecoin

  - title: Entertainment
    path: entertainment
    icon: mdi:filmstrip
    badges:
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:power
                size: 35px
                entity: switch.tv
                color: rgb(82,150,28)
                color_off:
                color_type: card
                name: TV
                state:
                  - value: 'on'
                    styles:
                      card:
                        - background: rgb(82,150,28)
                      icon:
                        - color: rgb(255,255,255)
                      name:
                        - color: rgb(255,255,255)
                  - value: 'off'
                    styles:
                      card:
                        - background: var(--primary-color)
                      icon:
                        - color: rgb(255,255,255)
                      name:
                        - color: rgb(255,255,255)
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:volume-minus
                size: 44px
                show_name: false
                action: call-service
                service: script.turn_on
                entity: script.tv_vol_down
              - type: "custom:button-card"
                icon: mdi:volume-mute
                size: 44px
                entity: switch.tv_mute
                show_name: false
                state:
                  - value: 'on'
                    styles:
                      icon:
                        - color: rgb(82,150,28)
                  - value: 'off'
                    styles:
                      icon:
                        - color: var(--primary-color)
              - type: "custom:button-card"
                icon: mdi:volume-plus
                size: 44px
                show_name: false
                action: call-service
                service: script.turn_on
                entity: script.tv_vol_up
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                name: Netflix
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: kodi.call_method
                service_data:
                  entity_id: media_player.tv_kodi
                  method: Addons.ExecuteAddon
                  addonid: plugin.video.netflix
                  params:
                    command: activate
              - type: "custom:button-card"
                name: Kodi
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: kodi.call_method
                service_data:
                  entity_id: media_player.tv_kodi
                  method: Input.Home
              - type: "custom:button-card"
                name: Plex
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: kodi.call_method
                service_data:
                  entity_id: media_player.tv_kodi
                  method: Addons.ExecuteAddon
                  addonid: script.plex
                  params:
                    command: activate
          - type: entities
            title: false
            show_header_toggle: false
            entities:
              - entity: switch.tv
 #               - entity: switch.speaker
 #               - entity: input_number.luther_sound_volume
              - entity: switch.games
      - type: media-control
        entity: media_player.luther_universal_tv
 #       - type: media-control
 #         entity: media_player.luther_universal_audio

  - title: Cameras
    path: cctv
    icon: mdi:camera-iris
    badges:
    cards:
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_front
          - type: entities
            title: Front
            show_header_toggle: false
            entities:
              - script.blink_front_capture_script
              - sensor.blink_front_temperature
              - binary_sensor.blink_front_battery
              - binary_sensor.blink_front_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_back
          - type: entities
            title: Back
            show_header_toggle: false
            entities:
              - script.blink_back_capture_script
              - sensor.blink_back_temperature
              - binary_sensor.blink_back_battery
              - binary_sensor.blink_back_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_indoor_front
          - type: entities
            title: Indoor Front
            show_header_toggle: false
            entities:
              - script.blink_indoor_front_capture_script
              - sensor.blink_indoor_front_temperature
              - binary_sensor.blink_indoor_front_battery
              - binary_sensor.blink_indoor_front_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_indoor_back
          - type: entities
            title: Indoor Back
            show_header_toggle: false
            entities:
              - script.blink_indoor_back_capture_script
              - sensor.blink_indoor_back_temperature
              - binary_sensor.blink_indoor_back_battery
              - binary_sensor.blink_indoor_back_camera_armed

  - title: Outdoors
    path: outdoors
    icon: mdi:pine-tree
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - sensor.dark_sky_precip_intensity
          - sun.sun
          - sensor.moon
          - sensor.dark_sky_uv_index
          - sensor.u_s_air_pollution_level
          - sensor.u_s_air_quality_index
          - sensor.u_s_main_pollutant
 #      - type: map
 #        title: Space Station
 #        aspect_ratio: 16:9
 #        default_zoom: 8
 #        entities:
 #          - binary_sensor.iss
 #      - type: entities
 #        title: Next Train
 #        show_header_toggle: false
 #        entities:
 #          - sensor.next_train_status
 #          - sensor.next_trains_estimated
 #          - sensor.next_trains_scheduled
 #          - sensor.next_trains_platform
 #      - type: plant-status
 #        entity: plant.flora_front_plant
 #      - type: plant-status
 #        entity: plant.flora_back_plant

  - title: Settings
    path: settings
    icon: mdi:settings
    badges:
    cards:
 #      - type: entities
 #        title: Protect
 #        show_header_toggle: false
 #        entities:
 #          - sensor.downstairs_nest_protect_battery_health
 #          - sensor.downstairs_nest_protect_co_status
 #          - sensor.downstairs_nest_protect_smoke_status
 #          - sensor.upstairs_nest_protect_battery_health
 #          - sensor.upstairs_nest_protect_co_status
 #          - sensor.upstairs_nest_protect_smoke_status
      - type: entities
        title: Internet
        show_header_toggle: false
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.ip_address
      - type: entities
        title: Bonsai
        show_header_toggle: false
        entities:
          - entity: sensor.memory_use_percent
          - entity: sensor.load_5m
          - entity: sensor.cpu_temperature
          - entity: sensor.since_last_boot_sycamore
          - entity: switch.pihole_sycamore_switch
          - type: section
            label: Containers
          - entity: switch.dockermon_blinkt
          - entity: switch.dockermon_nodered
          - entity: switch.dockermon_plex
          - entity: switch.dockermon_watchtower
      - type: entities
        title: Mycroft
        show_header_toggle: false
        entities:
          - entity: sensor.ram_use_mycroft
          - entity: sensor.cpu_use_mycroft
          - entity: sensor.cpu_temperature_mycroft
          - entity: sensor.since_last_boot_mycroft
          - entity: switch.pihole_mycroft_switch
      - type: entities
        title: Oak
        show_header_toggle: false
        entities:
          - entity: script.oak_on
          - type: section
            label: Containers
          - entity: switch.dockermon_plex_oak
          - entity: switch.dockermon_warrior
          - entity: switch.dockermon_watchtower_oak
          - entity: switch.dockermon_f_h
      - type: entities
        title: Settings
        show_header_toggle: false
        entities:
          - switch.presence_emulator
      - type: entities
        title: Ad Blocker
        show_header_toggle: true
        entities:
          - switch.pihole_sycamore_switch
          - switch.pihole_mycroft_switch
      - type: entities
        title: Blink
        show_header_toggle: false
        entities:
          - binary_sensor.blink_back_camera_armed
          - binary_sensor.blink_front_camera_armed
          - binary_sensor.blink_indoor_back_camera_armed
          - binary_sensor.blink_indoor_front_camera_armed
