title: Sycamore
resources:
  - url: /local/button-card.js?v=0.0.6
    type: module
views:
  - title: Home
    icon: mdi:home
    badges:
      - device_tracker.ge
      - device_tracker.sc
      - device_tracker.ti
      - device_tracker.gr
      - climate.hallway
      - sensor.hallway_thermostat_temperature
      - sensor.hallway_thermostat_target
      - sensor.hallway_thermostat_humidity
    cards:
      - type: entities
        show_header_toggle: true
        title: Lights
        entities:
          - light.back_door
          - switch.bedroom_light
          - switch.lounge_light_small
          - switch.lounge_light_tall
          - switch.office_light
      - type: entities
        show_header_toggle: true
        title: Lounge Lights
        entities:
          - switch.lounge_light_small
          - switch.lounge_light_tall
      - type: entities
        title: Calls
        show_header_toggle: false
        entities:
          - sensor.last_call
          - sensor.last_blocked_call
      - type: vertical-stack
        cards:
          - type: sensor
            hours_to_show: 24
            name: Power Consumption
            graph: line
            entity: sensor.emoncms104856_power_kw
            detail: 2
          - type: sensor
            graph: line
            entity: sensor.emoncms104902_meter_count
            name: Power Meter
            hours_to_show: 24
          - type: sensor
            graph: line
            entity: sensor.energybattery
            name: Meter Battery
            detail: 2
      - type: entities
        title: General
        show_header_toggle: false
        entities:
          - switch.general_switch
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.hallway
          - type: entities
            title: false
            show_header_toggle: false
            entities:
              - switch.hot_water
      - type: sensor
        graph: line
        entity: sensor.hallway_thermostat_temperature
        name: Indoor Temperature
        detail: 2
      - type: entities
        title: Coins
        show_header_toggle: false
        entities:
          - sensor.bitcoin
          - sensor.bitcoin_cash
          - sensor.dash
          - sensor.ethereum
          - sensor.ripple
          - sensor.litecoin

  - title: Entertainment
    path: entertainment
    icon: mdi:filmstrip
    badges:
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:power
                size: 35px
                entity: switch.tv
                color: rgb(82,150,28)
                color_off:
                color_type: card
                name: TV
                state:
                  - value: 'on'
                    styles:
                      card:
                        - background: rgb(82,150,28)
                      icon:
                        - color: rgb(255,255,255)
                      name:
                        - color: rgb(255,255,255)
                  - value: 'off'
                    styles:
                      card:
                        - background: var(--primary-color)
                      icon:
                        - color: rgb(255,255,255)
                      name:
                        - color: rgb(255,255,255)
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                icon: mdi:volume-minus
                size: 44px
                show_name: false
                action: call-service
                service: script.turn_on
                entity: script.tv_vol_down
              - type: "custom:button-card"
                icon: mdi:volume-mute
                size: 44px
                entity: switch.tv_mute
                show_name: false
                state:
                  - value: 'on'
                    styles:
                      icon:
                        - color: rgb(82,150,28)
                  - value: 'off'
                    styles:
                      icon:
                        - color: var(--primary-color)
              - type: "custom:button-card"
                icon: mdi:volume-plus
                size: 44px
                show_name: false
                action: call-service
                service: script.turn_on
                entity: script.tv_vol_up
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                name: Netflix
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: script.turn_on
                entity: script.tv_netflix
              - type: "custom:button-card"
                name: Kodi
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: script.turn_on
                entity: script.tv_kodi
              - type: "custom:button-card"
                name: Plex
                styles:
                  card:
                    - color: rgb(255,255,255)
                    - background: rgb(112,55,178)
                    - height: 56px
                show_icon: false
                action: call-service
                service: script.turn_on
                entity: script.tv_plex
          - type: entities
            title: false
            show_header_toggle: false
            entities:
              - entity: switch.tv
              - entity: switch.speaker
              - entity: input_number.luther_sound_volume
              - entity: switch.games
      - type: media-control
        entity: media_player.luther_universal_tv
      - type: media-control
        entity: media_player.luther_universal_audio

  - title: Cameras
    path: cctv
    icon: mdi:camera-iris
    badges:
    cards:
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_front
          - type: entities
            title: Front
            show_header_toggle: false
            entities:
              - script.blink_front_capture_script
              - sensor.blink_front_temperature
              - sensor.blink_front_battery
              - binary_sensor.blink_front_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_back
          - type: entities
            title: Back
            show_header_toggle: false
            entities:
              - script.blink_back_capture_script
              - sensor.blink_back_temperature
              - sensor.blink_back_battery
              - binary_sensor.blink_back_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_indoor_front
          - type: entities
            title: Indoor Front
            show_header_toggle: false
            entities:
              - script.blink_indoor_front_capture_script
              - sensor.blink_indoor_front_temperature
              - sensor.blink_indoor_front_battery
              - binary_sensor.blink_indoor_front_camera_armed
      - type: vertical-stack
        cards:
          - type: picture-entity
            entity: camera.blink_indoor_back
          - type: entities
            title: Indoor Back
            show_header_toggle: false
            entities:
              - script.blink_indoor_back_capture_script
              - sensor.blink_indoor_back_temperature
              - sensor.blink_indoor_back_battery
              - binary_sensor.blink_indoor_back_camera_armed

  - title: Outdoors
    path: outdoors
    icon: mdi:pine-tree
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: Weather
        show_header_toggle: false
        entities:
          - sensor.dark_sky_precip_intensity
          - sensor.pollen_count
          - sun.sun
          - sensor.moon
          - sensor.dark_sky_uv_index
          - sensor.us_air_pollution_level
          - sensor.us_air_quality_index
          - sensor.us_main_pollutant
      - type: entities
        title: Next Train
        show_header_toggle: false
        entities:
          - sensor.next_train_status
          - sensor.next_trains_estimated
          - sensor.next_trains_scheduled
          - sensor.next_trains_platform
#      - type: plant-status
#        entity: plant.flora_front_plant
#      - type: plant-status
#        entity: plant.flora_back_plant

  - title: Settings
    path: settings
    icon: mdi:settings
    badges:
    cards:
      - type: entities
        title: Protect
        show_header_toggle: false
        entities:
          - sensor.downstairs_nest_protect_battery_health
          - sensor.downstairs_nest_protect_co_status
          - sensor.downstairs_nest_protect_smoke_status
          - sensor.upstairs_nest_protect_battery_health
          - sensor.upstairs_nest_protect_co_status
          - sensor.upstairs_nest_protect_smoke_status
      - type: entities
        title: Internet
        show_header_toggle: false
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.ip_address
      - type: entities
        title: Bonsai
        show_header_toggle: false
        entities:
          - entity: sensor.memory_use_percent
          - entity: sensor.load_5m
          - entity: sensor.cpu_temperature
          - entity: sensor.since_last_boot_sycamore
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_ads_percentage_blocked_today
          - entity: switch.pihole_sycamore_switch
          - type: section
            label: Containers
          - entity: switch.dockermon_blinkt
          - entity: switch.dockermon_ncid
          - entity: switch.dockermon_nodered
          - entity: switch.dockermon_watchtower
      - type: entities
        title: Mycroft
        show_header_toggle: false
        entities:
          - entity: sensor.ram_use_mycroft
          - entity: sensor.cpu_use_mycroft
          - entity: sensor.cpu_temperature_mycroft
          - entity: sensor.since_last_boot_mycroft
          - entity: sensor.pi_hole_ads_blocked_today_2
          - entity: sensor.pi_hole_ads_percentage_blocked_today_2
          - entity: switch.pihole_mycroft_switch
      - type: entities
        title: Oak
        show_header_toggle: false
        entities:
          - entity: script.oak_on
      - type: entities
        title: Settings
        show_header_toggle: false
        entities:
          - switch.presence_emulator
      - type: entities
        title: Ad Blocker
        show_header_toggle: true
        entities:
          - switch.pihole_sycamore_switch
          - switch.pihole_mycroft_switch
      - type: entities
        title: Blink
        show_header_toggle: false
        entities:
          - binary_sensor.blink_back_camera_armed
          - binary_sensor.blink_front_camera_armed
          - binary_sensor.blink_indoor_back_camera_armed
          - binary_sensor.blink_indoor_front_camera_armed
