version: '3.1'
services:
  pihole:
    image: pihole/pihole:4.3.1-4_armhf
    volumes:
      - "/var/log/pihole.log:/var/log/pihole.log"
      - "/media/data/Containers/pihole:/etc/pihole"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80"
    cap_add:
      - NET_ADMIN
    environment:
    dns:
      - 127.0.0.1
      - 1.1.1.1
    extra_hosts:
    secrets:
      - web-password
    restart: always
    container_name: pihole
secrets:
  web-password:
    file: ./secrets/web-password
