version: '3.1'
services:
  pihole:
    image: pihole/pihole:latest
    volumes:
      - "/media/saga/Media/Containers/pihole:/etc/pihole"
    ports:
      - "192.168.11.5:53:53/tcp"
      - "192.168.11.5:53:53/udp"
      - "192.168.11.5:67:67/udp"
      - "8053:80"
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Stockholm
      - VIRTUAL_HOST=pihole.saga.lan
    dns:
      - 127.0.0.1
      - 1.1.1.1
    extra_hosts:
      - "columbo columbo.lan:192.168.11.1"
      - "saga saga.lan:192.168.11.5"
      - "nodered nodered.saga.lan:192.168.11.5"
      - "pihole pihole.saga.lan:192.168.11.5"
      - "bonsai bonsai.lan:192.168.11.3"
      - "miniflux miniflux.saga.lan:192.168.11.5"
      - "deconz.saga.lan:192.168.11.5"
      - "plex.saga.lan:192.168.11.5"
    secrets:
      - web-password
    restart: always
    container_name: pihole
secrets:
  web-password:
    file: ./secrets/web-password
