version: '2'
services:
    pihole:
        image: diginc/pi-hole:arm
        volumes:
            - "/var/log/pihole.log:/var/log/pihole.log"
            - "/mnt/data/Containers/pihole:/etc/pihole"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8053:80"
        cap_add:
            - NET_ADMIN
        environment:
            - ServerIP=
            - VIRTUAL_HOST=
            - DNS1=
            - DNS2=
            - WEBPASSWORD=
        extra_hosts:
            - "sycamore sycamore.lan:192.168.11.2"
            - "nodered nodered.sycamore.lan:192.168.11.2"
            - "sync sync.sycamore.lan:192.168.11.2"
            - "plex plex.sycamore.lan:192.168.11.2"
            - "pihole pihole.sycamore.lan:192.168.11.2"
            - "ziggy ziggy.sycamore.lan:192.168.11.3"
        restart: always
        container_name: pihole
