version: '2'
services:
    jottacloud:
        image: jottacloud:latest
        volumes:
            - "/media/saga/Media/Music:/backup/Music:ro"
            - "/media/saga/Media/Photos:/backup/Photos:ro"
            - "/media/saga/Media/TV:/backup/TV:ro"
            - "/media/saga/Media/Films:/backup/Films:ro"
            - "/media/saga/Media/Containers/jottacloud/data:/var/lib/jottad"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "14443:14443"
        environment:
            - PUID=1000
            - PGID=1000
            - JOTTA_DEVICE=saga
            - JOTTA_SCANINTERVAL=1h
        network_mode: "host"
        restart: always
        container_name: jottacloud
