version: "2"
services:
    deconz:
        image: marthoc/deconz:latest
        volumes:
            - "/media/saga/Media/Containers/deconz/data:/root/.local/share/dresden-elektronik/deCONZ"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            - DECONZ_WEB_PORT=8020
            - DECONZ_WS_PORT=4043
            - DEBUG_INFO=1
            - DEBUG_APS=0
            - DEBUG_ZCL=0
            - DEBUG_ZDP=0
            - DEBUG_OTAU=0
        devices:
            - "/dev/ttyACM0:/dev/ttyACM0"
        container_name: deconz
        network_mode: host
        restart: always
