version: '3'
services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: always
    command: watchtower dockermon plex pihole mqtt warrior miniflux miniflux_db caddy --cleanup -i 86400
