version: '2'
services:
    nodered:
        image: nodered
        volumes:
            - "/media/data/Containers/node-red:/data"
            - "/media/data/Containers/homeassistant:/hass"
            - "/media/data/Containers/ncid:/ncid"
        ports:
            - "1880:1880"
        environment:
            - FLOWS=flows.json
        network_mode: "host"
        restart: always
        container_name: nodered
