alias: Arrive
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  to: 'home'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: automation.away_hallway_light
  - service: homeassistant.turn_off
    data:
      entity_id: automation.away_lounge_light_small
  - service: homeassistant.turn_off
    data:
      entity_id: automation.away_lounge_light_tall
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "opcode": "11" }'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_front
  - delay: '00:00:10'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_back
  - delay: '00:00:10'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - delay: '00:00:10'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_back
