alias: Arrive Scott
initial_state: true
trigger:
  platform: state
  entity_id: person.scott
  to: 'home'
action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.docker_watchtower
