alias: Arrive Lights
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  to: 'home'
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:45:00"
action:
  - service: light.turn_on
    data:
      entity_id: light.lounge_light_small
      brightness: 180
      transition: 2
  - service: light.turn_on
    data:
      entity_id: light.lounge_light_tall
      brightness: 180
      transition: 2
  - service: light.turn_on
    data:
      entity_id: light.cabinet_1
      brightness: 255
      rgb_color: [255, 146, 228]
      transition: 2
  - service: light.turn_on
    data:
      entity_id: light.cabinet_2
      brightness: 255
      kelvin: 455
      transition: 2
