alias: Arrive Lights
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  to: 'home'
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:45:00"
action:
  - service: light.turn_on
    data:
      entity_id: light.hallway
      brightness: 255
  - service: light.turn_on
    data:
      entity_id: light.lounge_light_small
      brightness: 180
  - service: light.turn_on
    data:
      entity_id: light.lounge_light_tall
      brightness: 180
  - service: homeassistant.turn_on
    data:
      entity_id: switch.cloud
