alias: Away Lounge Light Small
initial_state: true
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ states.sun.sun.attributes.elevation }}'
    below: -3
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.presence_emulator
        state: 'on'
      - condition: state
        entity_id: group.people
        state: 'not_home'
      - condition: time
        before: '22:30:00'
action:
  - delay: "00:{{ range(01,59) | random }}:{{ range(01,59) | random }}"
  - service: light.turn_on
    data:
      entity_id: light.lounge_light_small
      brightness: 125
  - delay: "0{{ range(1,2) | random }}:{{ range(01,59) | random }}:00"
  - service: light.turn_off
    data:
      entity_id: light.lounge_light_small
