alias: Blink Battery Low
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.blink_front_door_battery
    to: 'on'
  - platform: state
    entity_id: sensor.blink_kitchen_battery
    to: 'on'
  - platform: state
    entity_id: sensor.blink_street_battery
    to: 'on'
action:
  - service: notify.all
    data:
      title: "{{'\U0001F4F9'}} Camera Battery Low!"
      message: "{{ trigger.entity_id }} battery level has dropped to {{ trigger.to_state.state }}%"
      data:
        clickAction: "/lovelace/cctv"
