alias: Blink Trigger Kitchen
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.blink_kitchen_motion_detected
  to: 'on'
action:
  - service: script.blink_kitchen_capture_script
