alias: Blink Trigger Indoor Back
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.blink_indoor_back_motion_detected
  to: 'on'
action:
  - service: script.blink_indoor_back_capture_script