alias: Blink Trigger Indoor Front
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.blink_indoor_front_motion_detected
  to: 'on'
action:
  - service: script.blink_indoor_front_capture_script