alias: Turn on cloud lamp with movement
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor
  to: 'on'
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:45:00"
action:
  service: switch.turn_on
  entity_id: switch.cloud
