alias: Turn off cloud lamp 10 minutes after last movement
trigger:
  platform: state
  entity_id: binary_sensor.tradfri_motion_sensor
  to: 'off'
  for:
    minutes: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: time
      after: '18:00:00'
action:
  service: switch.turn_off
  entity_id: switch.cloud
