alias: Turn Off Fan in the Morning
initial_state: true
trigger:
  platform: time
  at: '08:30:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: switch.auto_fan
      state: 'on'
    - condition: state
      entity_id: group.people
      state: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: fan.fan
