alias: Kodi Play
trigger:
  platform: state
  entity_id: media_player.tv_kodi
  to: 'playing'
action:
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "icon": "play", "r":0, "g":255, "b":0 }'