alias: Kodi Paused
trigger:
  platform: state
  entity_id: media_player.tv_kodi
  to: 'paused'
action:
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "icon": "pause", "r":255, "g":255, "b":255 }'