alias: Leave Scott
initial_state: true
trigger:
  platform: state
  entity_id: person.scott
  from: 'home'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.dockermon_watchtower
