alias: Leave Hallyway Light Off (10 Minutes)
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  from: 'home'
  to: 'not_home'
  for:
    minutes: 10
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  service: light.turn_off
  entity_id: light.hallway
