alias: Leave Hallyway Light Off (5 Minutes)
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  from: 'home'
  to: 'not_home'
  for:
    minutes: 5
action:
  service: light.turn_off
  entity_id: light.hallway
