alias: Leave Scott
initial_state: true
trigger:
  platform: state
  entity_id: device_tracker.sc
  from: 'home'
  to: 'not_home'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.dockermon_watchtower
