alias: Leave
initial_state: true
trigger:
  platform: state
  entity_id: group.people
  from: 'home'
action:
  - service: homeassistant.turn_on
    data:
      entity_id: automation.away_lounge_light_small
  - service: homeassistant.turn_on
    data:
      entity_id: automation.away_lounge_light_tall
  - service: alarm_control_panel.alarm_arm_away
    data:
      entity_id: alarm_control_panel.blink_hem
#  - service: mqtt.publish
#    data:
#      topic: sycamore/unicorn
#      payload: '{ "opcode": "10" }'
#  - service: camera.enable_motion_detection
#    data:
#      entity_id: camera.blink_front
#  - delay: '00:00:10'
#  - service: camera.enable_motion_detection
#    data:
#      entity_id: camera.blink_back
#  - delay: '00:00:10'
#  - service: camera.enable_motion_detection
#    data:
#      entity_id: camera.blink_indoor_front
#  - delay: '00:00:10'
#  - service: camera.enable_motion_detection
#    data:
#      entity_id: camera.blink_indoor_back
