alias: Dim Cabinet When Media Playing
initial_state: true
trigger:
  - platform: state
    entity_id: media_player.tv
    to: 'playing'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: light.cabinet_1
      state: 'on'
    - condition: state
      entity_id: light.cabinet_2
      state: 'on'
action:
  - service: light.turn_on
    data:
      entity_id: light.cabinet_1
      brightness: 100
      rgb_color: [255, 146, 228]
      transition: 1
  - service: light.turn_on
    data:
      entity_id: light.cabinet_2
      brightness: 100
      kelvin: 455
      transition: 1
