alias: Monk Finished Cleaning
trigger:
  - platform: state
    entity_id: sensor.xiaomi_vacuum_cleaner_total_clean_count
action:
  - service: notify.all
    data:
      title: "{{'\U0001F9F9'}} Monk finished cleaning"
      message: "Monk cleaned {{ (states('sensor.xiaomi_vacuum_cleaner_last_clean_area') | default(0) | round(2)) }}m² in {{ (states('sensor.xiaomi_vacuum_cleaner_last_clean_duration') | default(0) | float | timestamp_custom('%M:%S')) }}."
      data:
        timeout: 120
        clickAction: "/lovelace/dammsugare"
  - service: homeassistant.turn_off
    data:
      entity_id: group.monk_zones
