alias: Monk Finished Cleaning
trigger:
  - platform: state
    entity_id: sensor.xiaomi_vacuum_cleaner_total_clean_count
action:
  - service: notify.all
    data:
      title: "{{'\U0001F9F9'}} Monk finished cleaning"
      message: "Monk cleaned {{ sensor.xiaomi_vacuum_cleaner_last_clean_area }}m² in {{ sensor.xiaomi_vacuum_cleaner_last_clean_duration / 60 | round }} minutes."
      data:
        timeout: 120
        clickAction: "/lovelace/dammsugare"
  - service: homeassistant.turn_off
    data:
      entity_id: group.monk_zones
  - service: input_select.select_option
    data:
      entity_id: input_select.monk_fan_speed
      option: 'Standard'
