alias: Motion Turn Off Camera Lights
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.hallway
  to: 'off'
  for:
    minutes: 20
condition:
  condition: state
  entity_id: light.cameras
  state: 'on'
action:
  - service: light.turn_off
    data:
      entity_id: light.cameras
      transition: 3
