alias: Turn On DND at Night
initial_state: true
trigger:
  platform: time
  at: "22:30:00"
condition:
  - condition: state
    entity_id: group.people
    state: 'home'
action:
  - service: switch.turn_on
    data:
      entity_id: switch.do_not_disturb
