alias: Turn On Cabinet Lights At Sunet When Home
initial_state: true
trigger:
  platform: sun
  event: sunset
  offset: "-00:10:00"
condition:
  - condition: state
    entity_id: group.people
    state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.cabinet_1
      brightness: 255
      rgb_color: [255, 146, 228]
      transition: 3
  - service: light.turn_on
    data:
      entity_id: light.cabinet_2
      brightness: 255
      kelvin: 455
      transition: 3
