alias: Goodnight
initial_state: true
trigger:
  platform: time
  at: '23:30:00'
condition:
  - condition: state
    entity_id: group.people
    state: 'home'
action:
  - service: switch.turn_off
    entity_id: switch.fullykiosk_screen
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_front
  - delay: '00:00:02'
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_back
  - delay: '00:00:02'
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
