alias: Hemglass Here
initial_state: true
trigger:
  platform: template
  value_template: '{% set next = as_timestamp(states("sensor.hemglass")) %} {% set now = as_timestamp( now() ) %} {% if now >= ( next - 900 ) %}true{% endif %}'
action:
  - service: notify.all
    data:
      title: "{{'\U0001F368'}} Hemglass approaching"
      message: "ETA: {{ as_timestamp(states('sensor.hemglass')) | timestamp_custom('%A at %H:%M') }}"
      data:
        timeout: 900
        clickAction: "https://www.hemglass.se/sv/hitta-glassbilen/"
  # perhaps turn off automation
  - service: automation.turn_off
    entity_id:  automation.hemglass_here
  - delay: '24:00:00'
  # perhaps turn on automation
  - service: automation.turn_on
    entity_id:  automation.hemglass_here
