alias: Krisinformation
initial_state: true
trigger:
  platform: state
  entity_id: sensor.krisinformation
  to: "Alert"
action:
  - service: notify.all
    data:
      title: "{{'\U000126A0'}} Krisinformation"
      message: "{{states.sensor.krisinformation.attributes.messages[0].Headline}}"
      data:
        clickAction: "https://www.krisinformation.se/en"
        color: black
        transparency: "75%"
        icon:
            path: "/config/www/ha.png"
  - service: notify.lametric
    data:
      message: "Krisinformation: {{states.sensor.krisinformation.attributes.messages[0].Headline}}"
      data:
        sound: thunder
        icon: "a17908"
        cycles: 3
