alias: ISS Pass
initial_state: true
trigger:
  platform: template
  value_template: '{% set nextrise = as_timestamp(states.binary_sensor.iss.attributes.next_rise) %} {% set now = as_timestamp( now() ) %} {% if ( nextrise - 600 ) >= now %}true{% endif %}'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: sensor.dark_sky_summary
      state: 'Clear'
action:
  - service: notify.tv
    data:
      message: "{{'\U00002604'}} The space station will be passing soon: {{ as_timestamp(states.binary_sensor.iss.attributes.next_rise) | timestamp_custom('%A at %H:%M') }}"
      data:
        displaytime: 15000
  - service: notify.telegram_group
    data:
      message: "{{'\U00002604'}} The space station will be passing soon: {{ as_timestamp(states.binary_sensor.iss.attributes.next_rise) | timestamp_custom('%A at %H:%M') }}"
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "icon": "iss", "r":255, "g":255, "b":255, "opcode": "1", "text": "The space station will be passing soon!" }'
