alias: Notify Door Motion
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.post
  to: 'on'
condition:
  condition: time
  after: '09:00:00'
  before: '21:00:00'
action:
  - service: notify.all
    data:
      title: "{{'\U0001F4E8'}} Post? Zombies?"
      message: "It might be time to check the post box..."
      data:
        channel: Alert
        importance: max
        priority: high
        ttl: 0
        timeout: 600
        clickAction: "/lovelace/cctv"
