alias: Stop Warrior with Plex
initial_state: true
trigger:
  platform: template
  value_template: "{{ states('sensor.plex') | int(default=0) == 0 }}"
  for:
    minutes: 10
action:
  - service: homeassistant.turn_off
    data:
      entity_id: switch.docker_warrior
