alias: Nest Summary Automation
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.hallway_temperature
action:
  - service: mqtt.publish
    data_template:
      topic: sycamore/unicorn
      payload: '{ "opcode": "1", "text": "{{ states.sensor.hallway_temperature.state }}~degrsc" }'