alias: Sycamore Away Lights Office
initial_state: true
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -4
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.presence_emulator
        state: 'on'
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: time
        before: '23:00:00'
action:
  - delay: '00:{{ range(01,30) | random | int }}:{{ range(01,59) | random | int }}'
  - service: homeassistant.turn_on
    data:
      entity_id: switch.office_light
  - delay: '0{{ range(1,2) | random | int }}:{{ range(01,50) | random | int }}:00'
  - service: homeassistant.turn_off
    data:
      entity_id: switch.office_light
