alias: Sycamore Smoke Warning
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.downstairs_nest_protect_smoke_status
    to: 'Warning'
  - platform: state
    entity_id: sensor.upstairs_nest_protect_smoke_status
    to: 'Warning'
action:
  - service: notify.all
    data:
      message: "{{ trigger.entity_id }} just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
      title: 'Sycamore: Smoke Warning!'