alias: Leave Sycamore Light Off (10 Minutes)
initial_state: true
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'home'
  to: 'not_home'
  for:
    minutes: 10
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  service: homeassistant.turn_off
  entity_id: light.back_door