alias: Sycamore Away Light Tall
initial_state: true
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ states.sun.sun.attributes.elevation }}'
    below: -3
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: switch.presence_emulator
        state: 'on'
      - condition: state
        entity_id: group.all_devices
        state: 'not_home'
      - condition: time
        before: '21:30:00'
action:
  - delay: '00:{{ range(01,59) | random | int }}:{{ range(01,59) | random | int }}'
  - service: homeassistant.turn_on
    data:
      entity_id: switch.lounge_light_tall
  - delay: '0{{ range(1,3) | random | int }}:{{ range(30,59) | random | int }}:00'
  - service: homeassistant.turn_off
    data:
      entity_id: switch.lounge_light_tall
