alias: Arrive at Sycamore
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'not_home'
  to: 'home'
action:
  - service: climate.set_away_mode
    data:
      away_mode: false
  - service: blink.arm_camera
    data:
      device_armed: "False"
      friendly_name: "Back"
  - service: blink.arm_camera
    data:
      device_armed: "False"
      friendly_name: "Indoor Front"
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "opcode": "11" }'
  - delay: '00:01:00'
  - service: tts.google_say
    data:
      entity_id: media_player.luther_audio
      message: 'Welcome home!'


