alias: Goodmorning
trigger:
  platform: time
  at: '07:00:00'
condition:
  - condition: state
    entity_id: group.all_devices
    state: 'home'
action:
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_back
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_back
