alias: Leave Sycamore
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'home'
  to: 'not_home'
action:
  - service: climate.set_away_mode
    data:
      away_mode: true
  - service: ifttt.trigger
    data:
      event: 'arm_sycamore'
  - service: blink.arm_camera
    data:
      device_armed: "True"
      friendly_name: "Back"
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "opcode": "10" }'