alias: Goodnight
trigger:
  platform: time
  at: '23:00:00'
condition:
  - condition: state
    entity_id: group.all_devices
    state: 'home'
action:
  - service: blink.arm_camera
    data:
      device_armed: "True"
      friendly_name: "Back"
  - service: blink.arm_camera
    data:
      device_armed: "True"
      friendly_name: "Indoor Front"