alias: Arrive at Sycamore
initial_state: true
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'not_home'
  to: 'home'
action:
  - service: homeassistant.turn_off
    data:
      entity_id: automation.sycamore_away__light_small
  - service: homeassistant.turn_off
    data:
      entity_id: automation.sycamore_away__light_tall
  - service: homeassistant.turn_off
    data:
      entity_id: automation.sycamore_away__lights_back
  - service: homeassistant.turn_off
    data:
      entity_id: automation.sycamore_away__lights_bedroom
  - service: climate.turn_on
    data:
      entity_id: climate.hallway
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "opcode": "11" }'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_back
  - delay: '00:00:02'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - delay: '00:00:02'
  - service: camera.disable_motion_detection
    data:
      entity_id: camera.blink_indoor_back
