alias: Goodnight
initial_state: true
trigger:
  platform: time
  at: '23:30:00'
condition:
  - condition: state
    entity_id: group.all_devices
    state: 'home'
action:
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_back
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_back