alias: Leave Sycamore
initial_state: true
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'home'
  to: 'not_home'
action:
  - service: climate.set_away_mode
    data:
      away_mode: true
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_back
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_back
  - service: mqtt.publish
    data:
      topic: sycamore/unicorn
      payload: '{ "opcode": "10" }'