alias: Sycamore Smoke Emergency
initial_state: true
trigger:
  - platform: state
    entity_id: sensor.downstairs_nest_protect_smoke_status
    to: 'Emergency'
  - platform: state
    entity_id: sensor.upstairs_nest_protect_smoke_status
    to: 'Emergency'
action:
  - service: notify.all
    data:
      message: "{{ trigger.entity_id }} just changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
      title: 'Sycamore: Smoke Emergency!'
  - service: light.lifx_effect_pulse
    data:
      entity_id: light.back_door
      brightness: 255
      color_name: red
      period: 2
      cycles: 50
  - service: switch.turn_on
    entity_id: group.all_switches
  - service: nest.set_away_mode
    data:
      away_mode: away
      structure:
        - Sycamore
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_back
  - delay: '00:00:02'
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_front
  - delay: '00:00:02'
  - service: camera.enable_motion_detection
    data:
      entity_id: camera.blink_indoor_back
