alias: 'Telegram Announce'
initial_state: true
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/announce'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/announce@columbo_bot'
action:
  - service: notify.mycroft
    data_template:
      message: '{{ trigger.event.data.args | join(" ") }}'
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >-
        Your voice message was sent to all smart speakers.
