alias: 'Telegram Lights'
initial_state: true
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/lights'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/lights@columbo_bot'
action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >
        {% if states.group.lights.state != 'off' -%}
          There are
          {%- for entity_id in states.group.lights.attributes.entity_id if states(entity_id) == 'on' -%}
            {%- if states(entity_id) == 'on' %}
              {%- if loop.last %} {{ loop.index }}{%- endif -%}
            {%- endif -%}
          {%- endfor %} lights on right now:
          {%- for entity_id in states.group.lights.attributes.entity_id if states(entity_id) == 'on' -%}
            {% set parts = entity_id.split('.') -%}
            {%- if loop.first %} {% elif loop.last %} and the {% else %}, the {% endif -%}{{ states[parts[0]][parts[1]].name }}
          {%- endfor %}.
        {%- else -%}
          The are no lights on at the moment.
        {%- endif %}
      inline_keyboard:
        - 'Toggle All Lights:/lights_toggle'
        - 'Toggle Lounge Lights:/lights_lounge_toggle'
        - 'Toggle Bedroom Light:/lights_bedroom_toggle'
        - 'Toggle Backdoor Light:/lights_backdoor_toggle'
        - 'Cancel:/cancel'
