alias: 'Telegram Netflix'
initial_state: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/netflix'
action:
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      inline_keyboard: []
  - service: script.tv_netflix
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >
        Netflix is booting up, enjoy the watching!
