alias: 'Telegram Temperature'
initial_state: true
hide_entity: true
trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/temperature'
  - platform: event
    event_type: telegram_command
    event_data:
      command: '/temperature@columbo_bot'
action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.hallway
      temperature: '{{ trigger.event.data.args[0] | float }}'
      operation_mode: heat
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >-
        {%- if trigger.event.data.args[0] | float != 0.0 -%}
          Setting the thermostat to {{ trigger.event.data.args[0] | float }} degrees.
        {%- else -%}
          {{ trigger.event.data.args[0] }} doesn't look like a valid temperature.
        {%- endif -%}