alias: 'Telegram TV Off'
initial_state: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/tv_off'
action:
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      inline_keyboard: []
  - service: homeassistant.turn_off
    data:
      entity_id: switch.tv
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >
        The TV has been switched off!
