alias: 'Telegram Kodi'
initial_state: true
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/kodi'
action:
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      inline_keyboard: []
  - service: script.tv_kodi
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >
        A fine choice. Kodi is starting now.