alias: 'Telegram Media'
initial_state: true
hide_entity: true
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/media'
action:
  - service: telegram_bot.edit_replymarkup
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      inline_keyboard: []
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.chat_id }}'
      disable_notification: true
      message: >
        {% if is_state('switch.tv', 'on') -%}
          The TV is on and {{ states('media_player.luther_universal_tv') }}:
          {%- if states.media_player.luther_universal_tv.attributes['media_title'] %} {{ states.media_player.luther_universal_tv.attributes['media_title'] }}{%- elif states.media_player.luther_universal_tv.attributes['source'] %} {{ states.media_player.luther_universal_tv.attributes['source'] }}{%- endif -%}
        {%- else -%}
          The TV is currently switched off.
        {%- endif %}
      inline_keyboard: 
        - 'TV On:/tv_on, TV Off:/tv_off'
        - 'Cancel:/cancel'