alias: Turn Off Fan After 1 Hour At Night
initial_state: true
trigger:
  platform: state
  entity_id: fan.fan
  to: 'on'
  for:
    hours: 1
    minutes: 30
condition:
  condition: and
  conditions:
    - condition: time
      after: '22:00:00'
      before: '08:00:00'
    - condition: state
      entity_id: switch.auto_fan
      state: 'on'
    - condition: state
      entity_id: group.people
      state: 'home'
action:
  - service: homeassistant.turn_off
    entity_id: fan.fan
