alias: Washing Timer Finished
initial_state: true
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.washing
condition:
  condition: state
  entity_id: input_boolean.washing_timer_visibility
  state: 'on'
action:
  - service: notify.all
    data:
      title: "{{'\U0001F455'}} The washing is ready!"
      message: "Put down that cocktail and grab the washing."
      data:
        clickAction: "/lovelace/default_view"
