alias: Wilson Door Motion
initial_state: true
trigger:
  platform: state
  entity_id: binary_sensor.post
  to: 'on'
condition:
  - condition: state
    entity_id: group.people
    state: 'home'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.wilson
      media_content_id: /local/dooralarm.m4a
      media_content_type: music
