alias: Wilson Click On
initial_state: true
trigger:
  - platform: state
    entity_id:
      - switch.presence_emulator
      - script.blink_front_capture_script

      - switch.pihole_sycamore_switch
      - switch.dockermon_blinkt
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: switch.fullykiosk_screen
    state: 'on'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.wilson
      media_content_id: /local/on.m4a
      media_content_type: music
