alias: Wilson Click On
initial_state: true
trigger:
  - platform: state
    entity_id:
      - switch.presence_emulator
      - script.blink_front_capture_script
      - switch.cloud
      - light.hallway
      - light.lounge_light_tall
      - light.lounge_light_small
      - input_boolean.monk_clean_lounge
      - input_boolean.monk_clean_kitchen
      - input_boolean.monk_clean_bedroom
      - input_boolean.monk_clean_hall
      - input_boolean.monk_clean_office_gemma
      - input_boolean.monk_clean_office_scott
      - switch.dockermon_blinkt
      - switch.dockermon_nodered
      - switch.dockermon_watchtower
      - switch.dockermon_plex
      - switch.dockermon_plex_oak
      - switch.dockermon_warrior
      - switch.dockermon_watchtower_oak
      - switch.presence_emulator

      #- switch.pihole_sycamore_switch
      #- switch.pihole_mycroft_switch
    from: 'off'
    to: 'on'
condition:
  - condition: state
    entity_id: switch.fullykiosk_screen
    state: 'on'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.wilson
      media_content_id: /local/on.m4a
      media_content_type: music
