alias: Wilson Click Popup
initial_state: true
trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: browser_mod
      service: popup
condition:
  - condition: state
    entity_id: switch.fullykiosk_screen
    state: 'on'
action:
  - service: media_player.play_media
    data:
      entity_id: media_player.wilson
      media_content_id: /local/popup.m4a
      media_content_type: music
