alias: Wilson Auto Brightness
initial_state: true
trigger:
  - platform: sun
    event: sunset
    offset: "-00:15:00"
  - platform: sun
    event: sunrise
    offset: "-00:15:00"
action:
  - service_template: input_number.set_value
    data_template:
      entity_id: input_number.fullykiosk_brightness_slider
      value: >
        {% if is_state('sun.sun', 'above_horizon') %}
        90 {% else %}
        50 {% endif %}
